### Variables
@base_url = http://localhost:8001
@token = a44afda2435538e94e2b5947aef41676af829ebbfe07e3441f040fdfbe051e41

### Login
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "usuario": "admin",
  "contrasena": "admin123"
}

###

### Logout
POST {{base_url}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Verificar token
GET {{base_url}}/auth/verificar
Authorization: Bearer {{token}}